# Fabric Properties
# check these on https://modmuss50.me/fabric.html
deps.minecraft.min = 1.21.11
deps.minecraft.max = 1.21.11
deps.yarn_build = 5

# Versioned Dependencies
deps.silk = 1.11.5
deps.server_translations = 2.5.2+1.21.9-pre3
deps.fabric_api = 0.141.4+1.21.11
deps.sqlite_jdbc_module = minecraft-sqlite-jdbc
deps.sqlite_jdbc = 3.53.1.0+2026-05-07
